config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'products#index'

  get 'show/:id',                    to: 'products#show',             as: 'show'

  match '/',                         to: 'products#search_results',   as: 'search_results', :via => :post

  get 'sales',                       to: 'products#sales_filter',     as: 'sales'

  get 'recent',                      to: 'products#recent_filter',    as: 'recent'

  get 'customer',                    to: 'customer#view_customer',    as: 'customer'

  match '/products/add/:id',         to: 'products#add_item_to_cart', as: 'add_item_to_cart', id: /\d+/, :via => :get

  get '/products/checkout',          to: 'products#checkout',         as: 'checkout'
  match '/products/create.html.erb', to: 'products#create',           as: 'create', :via => :post

  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :province
  has_many :orders
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :customer
  has_many :products, through: :line_items
  has_many :line_items
  has_many :products
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  has_many :line_items
  has_many :orders, through: :line_items
  validates :name, presence: true, uniqueness: true
end

app/models/province.rb
class Province < ActiveRecord::Base
  has_many :customers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :build_cart

  def build_cart
    session[:cart] ||= []
  end

  private
  def all_categories
    Category.all
  end
  helper_method :all_categories

  private
  def all_provinces
    Province.all
  end
  helper_method :all_provinces
end

app/controllers/customer_controller.rb
class CustomerController < ApplicationController

  def view_customer
    @customers = Customer.all
    @provinces = Province.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  @products = Product.order(:name)
  @categories = Category.all
  @cart_items = get_cart_items
  end

  def show
    @product = Product.find(params[:id])
  end

  def search_results
    if params[:category_id].to_i == 0
      @products = Product.where("name LIKE '%#{params[:search_keywords]}%'")
    else
      @products = Product.where("name LIKE '%#{params[:search_keywords]}%' and category_id = #{params[:category_id]}")
    end
  @categories = Category.all
  end

  def sales_filter
    @products = Product.where("CAST(price AS STRING) LIKE '%45'")
    @categories = Category.all
  end

  def recent_filter
    @products = Product.where('created_at > :date', date: 1.week.ago)
    @categories = Category.all
  end

  def add_item_to_cart
    session[:cart] << params[:id]
    redirect_to root_path
  end

  def checkout
    @cart_items = session[:cart].map do |item|
      Product.find(item)
    end
  end

  def create
    @cart_items = session[:cart].map do |item|
      Product.find(item)
    end
    @customer = Customer.create
    @customer.province_id = params[:province]
    @customer.first_name = params[:first_name]
    @customer.last_name = params[:last_name]
    @customer.address = params[:address]
    @customer.city = params[:city]

    if @customer.save!
      @order = @customer.orders.build
      @order.status = 'pending'
      @order.gst = @customer.province.gst
      @order.pst = @customer.province.pst
      @order.hst = @customer.province.hst

      if @order.save!
        @cart_items.each do |item|
          @line_item = @order.line_items.build
          @line_item.quantity = 1
          @line_item.product = item
          @line_item.price = item.price
          @line_item.save!
        end
      end
    end
    reset_session
    redirect_to root_path
    flash[:alert] = 'Order succesfully completed'
  end

  private
  def get_cart_items
    session[:cart].map do |item|
      items = Product.find(item)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/customer/_customer.html.erb

<div class="items">
	<ul>
		<h3></h3>


		
		<li><strong>Name:</strong> <%= @customers.first_name, @customers.last_name %></li>

		<li><%= @customers.address %></li>
		<li> <%= @customers.city %>/</li>
		 <li><%= @customers.province %></li>
		<br>
		<li><%= @provinces.gst %></li>
		<li><%= @provinces.pst %></li>
		<li><%= @provinces.hst %></li>

		
	</ul>




</div>
<br>

app/views/customer/view_customer.html.erb
 <%= render @customer %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EccommerceProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<div class="page">	
	<%=  render 'shared/header' %>
	
	<%= yield %>
</div>




</body>
</html>

app/views/products/_cart.html.erb
<div id="cart">

  <h1>Shopping Cart</h1>

  <% @cart_items.each do |items| %>
  <ul>
    <li><%= items.name %></li>
    <li><%= number_to_currency items.price %></li>
  </ul>
  <% end %>


  <%= link_to 'Check Out', 'products/checkout' %>
</div>

app/views/products/_product.html.erb

<div class="items">


  <ul>
		<h3><%= link_to product.name, show_path(product) %></h3>


		
		<li><strong>Price:</strong> <%= number_to_currency product.price %></li>

		<li><%= product.description %></li>

        <li><%= link_to 'Add to Cart', add_item_to_cart_path(:id => product.id) %></li>
		<br>

		<li><strong>category:</strong><%= product.category.name %></li>
	</ul>




</div>
<br>


app/views/products/checkout.html.erb
<div id="checkout">
  <h2>Shopping Cart Checkout</h2>

  <h3>Items</h3>
  <% @cart_items.each do |item| %>
  <ul>
    <li>Image placeHolder</li>
    <li><%= item.name %></li>
    <li><%= item.description %></li>
    <li><%= number_to_currency item.price %></li>
    <% end %>
  </ul>

  <h3>Enter Your Information</h3>
  <%= form_tag create_path, :authenticity_token => true do %>
  <label for="first_name">First Name</label>
      <input type="text", name="first_name"/>
      <br/>
  <label for="last_name">Last Name</label>
  <input type="text", name="last_name"/>
  <br/>
      <select name='province'>
        <%= options_from_collection_for_select(all_provinces, 'id', 'name') %>
      </select>
      <br/>
  <label for="Address">Address</label>
  <input type="text", name="address"/>
  <br/>
  <label for="City">City</label>
  <input type="text", name="city"/>
  <br/>
      <input type="submit" value="Submit"/>
      <% end %>
</div>

app/views/products/index.html.erb



<h2>All Products</h2>

<p>Products table size: <%= @products.size %></p>
<%= session[:cart].inspect %>

<%= render @products %>
<%= render partial: 'products/cart' %>


app/views/products/recent_filter.html.erb
<%= render @products %>

app/views/products/sales_filter.html.erb
<%= render @products %>

app/views/products/search_results.html.erb
<h1>Search Results</h1>

<% if @products.size.zero? %>
		<p>No Products Were Found</p>
	<% else %>
		<p><%= pluralize(@products.size, 'Product') %> Found</p>
		<%= render @products %>
	<% end %>

app/views/products/show.html.erb
<%= render @product %>

app/views/shared/_header.html.erb

<%= form_tag search_results_path do %>
	<%= text_field_tag :search_keywords %>
	<select name='category_id'>
		<option value="0">All</option>
		<%= options_from_collection_for_select(all_categories, 'id', 'name') %>
		<%= submit_tag 'Search' %>
	</select>
	
	
<% end %>